version: '2'

services:
    rest-api:
        image: nginx:latest
        ports:
            - 8000:80
        volumes:
            - .:/var/www/html/
            - ./docker/rest-api/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm

    php-fpm:
        container_name: portal-php
        build: docker/php-fpm
        volumes:
            - .:/var/www/html/:rw
        links:
            - database

    database:
        container_name: portal-database
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            MYSQL_ROOT_PASSWORD: root
            PMA_HOST: database
        ports:
            - 8001:80
